### ISSUE TITLE
Does migration really need to set role "postgres"?

### ISSUE THREAD

**Issue by Kaurin** [bewcloud/bewcloud#17]
Hi,

I am trying to containerize your application for my Kubernetes cluster. I think I'm close now, but some snags are popping up.

Namely, I have my init container use the same env vars as the main container, which are limited to only use the `app` database within the postgres cluster.

This is the error that's being thrown:

```
Running "001-base.pgsql"...
Failed!
Running "002-news-app.pgsql"...
PostgresError: must be able to SET ROLE "postgres"
    at Connection.#simpleQuery (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:697:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Connection.query (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:977:18)
    at async Client.#executeQuery (https://deno.land/x/postgres@v0.19.2/client.ts:256:12)
    at async Client.queryObject (https://deno.land/x/postgres@v0.19.2/client.ts:434:12)
    at async Database.query (file:///app/lib/interfaces/database.ts:69:20)
    at async runMigrations (file:///app/migrate-db.ts:70:7)
    at async file:///app/migrate-db.ts:86:1 {
  fields: {
    severity: "ERROR",
    code: "42501",
    message: 'must be able to SET ROLE "postgres"',
    file: "acl.c",
    line: "5194",
    routine: "check_can_set_role"
  },
  query: undefined,
  name: "PostgresError"
}
Failed!
```

I do have the option of running these migrations with the postgres role, but I thought it better to ask here if this can be handled upstream.

Thanks and good luck with the project!

**Comment by BrunoBernardino** [comment]
Thanks @Kaurin that's a good question. I guess technically there's a few PostgreSQL instructions/commands that aren't _necessary_ in the migration, it's just how I've exported from the `pg_dump` command (IIRC). That's something that can likely be improved. A PR is welcome!
