### ISSUE TITLE
An error occurred during route handling or page rendering

### ISSUE THREAD

**Issue by Kaurin** [bewcloud/bewcloud#19]
This happens after I try to log in with a freshly created user

![image](https://github.com/user-attachments/assets/82ad8a2b-83c3-40ba-95d5-2e0436f5412c)

Logs:
```
2024-11-01T03:16:18.010Z - [304] GET http://bewcloud.kube.example.com/styles.css
An error occurred during route handling or page rendering.
DataError: Key length is zero
    at importKeyHMAC (ext:deno_crypto/00_crypto.js:2988:11)
    at SubtleCrypto.importKey (ext:deno_crypto/00_crypto.js:984:16)
    at generateKey (file:///app/lib/auth.ts:28:23)
    at generateToken (file:///app/lib/auth.ts:128:21)
    at createSessionCookie (file:///app/lib/auth.ts:205:23)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async createSessionResponse (file:///app/lib/auth.ts:191:30)
    at async handleLogging (file:///app/routes/_middleware.tsx:66:22)
    at async handleContextState (file:///app/routes/_middleware.tsx:60:22)
    at async handleCors (file:///app/routes/_middleware.tsx:25:22)
2024-11-01T03:16:31.938Z - [304] GET http://bewcloud.kube.example.com/styles.css
```

**Comment by BrunoBernardino** [comment]
@Kaurin it seems your `.env` file is either not being loaded, or one of these variables is empty: https://github.com/bewcloud/bewcloud/blob/560ea569a0dee3db26e46b365d0d371f090bc467/.env.sample#L11-L12

**Comment by Kaurin** [comment]
That fixed it! Both were missing.
