### ISSUE TITLE
Will not run properly on TrueNAS SCALE

### ISSUE THREAD

**Issue by vodkapmp** [bewcloud/bewcloud#36]
I'm trying to run bewcloud on TrueNAS SCALE, and I seem to be having an issue getting it to run.

The app itself will start without an .env file and without any environment variables.
TrueNAS SCALE doesn't support using .env files, so I've added everything from it to my environment variables instead. I am uncertain if this is the reason for the issues I'm having.

When I do this, the app just constantly restarts with this repeating in the logs:
```
2024-12-29 17:25:19.421353+00:00caCertificates: [await Deno.readTextFile(POSTGRESQL_CAFILE)],
2024-12-29 17:25:19.421369+00:00[0m[31m                                ^[0m
2024-12-29 17:25:19.421390+00:00at [0m[1m[3mObject.readTextFile[0m ([0m[36mext:deno_fs/30_fs.js[0m:[0m[33m783[0m:[0m[33m24[0m)
2024-12-29 17:25:19.421403+00:00at [0m[36mfile:///app/lib/interfaces/database.ts[0m:[0m[33m15[0m:[0m[33m33[0m
2024-12-29 17:25:26.827091+00:00[0m[1m[31merror[0m: Uncaught (in promise) NotFound: No such file or directory (os error 2): readfile '""': No such file or directory (os error 2): readfile '""': No such file or directory (os error 2)
```
If I remove `POSTGRESQL_CAFILE=""` from my variables, it goes past this and the logs say:
```
2024-12-29 15:50:03.389739+00:00Crons starting...
2024-12-29 15:50:03.400870+00:00Using snapshot found at [36m/app/_fresh[39m
2024-12-29 15:50:03.403969+00:002024-12-29T15:50:03.403969168Z
2024-12-29 15:50:03.404045+00:00[48;5;121m[38;5;0m 🍋 Fresh ready [39m[49m
2024-12-29 15:50:03.404071+00:00[1mLocal:[22m [36mhttp://localhost:8000/[39m
2024-12-29 15:50:03.404094+00:002024-12-29T15:50:03.404094674Z
```
But now when I go into the container via shell to run `make migrate-db` in `/app` I just get this error:
```
$ make migrate-db
deno run --allow-net --allow-read --allow-env migrate-db.ts
Running "001-base.pgsql"...
Failed!
Error: failed to lookup address information: Name or service not known
    at async Object.connect (ext:deno_net/01_net.js:583:55)
    at async Connection.#openConnection (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:266:18)
    at async Connection.#startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:342:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:494:11)
    at async Client.connect (https://deno.land/x/postgres@v0.19.2/client.ts:233:7)
    at async Database.connectToPostgres (file:///app/lib/interfaces/database.ts:46:7)
    at async Database.query (file:///app/lib/interfaces/database.ts:85:7)
    at async runMigrations (file:///app/migrate-db.ts:73:7)
    at async file:///app/migrate-db.ts:91:3
Error: failed to lookup address information: Name or service not known
    at async Object.connect (ext:deno_net/01_net.js:583:55)
    at async Connection.#openConnection (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:266:18)
    at async Connection.#startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:342:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:494:11)
    at async Client.connect (https://deno.land/x/postgres@v0.19.2/client.ts:233:7)
    at async Database.connectToPostgres (file:///app/lib/interfaces/database.ts:46:7)
    at async Database.query (file:///app/lib/interfaces/database.ts:85:7)
    at async runMigrations (file:///app/migrate-db.ts:73:7)
    at async file:///app/migrate-db.ts:91:3
make: *** [Makefile:20: migrate-db] Error 1
```

**Comment by BrunoBernardino** [comment]
Hi @vodkapmp ! It seems your initial problem was related to the fact the environment variable wasn't empty but rather two double quotes. Probably something with the OS differences.

The `.env` file shouldn't be necessary as long as the environment variables exist for the docker container.

As for the `make migrate-db` command not working, the error is how the hostname isn't known. Whatever you're setting up for `POSTGRESQL_HOST` apparently isn't resolvable. Are you connecting via container name, external ip/port/host, or in some other way?

**Comment by vodkapmp** [comment]
> Hi @vodkapmp ! It seems your initial problem was related to the fact the environment variable wasn't empty but rather two double quotes. Probably something with the OS differences.

This, makes a lot of sense. I should've realised this when it complained about `"5432"` not being a valid port.
Removing the "" from every environmental value solved both issues :)

I guess the hostname `"postgres15bc"` doesn't resolve to `postgres15bc`....

**Comment by BrunoBernardino** [comment]
Can you try with an IP + port or direct socket path?

**Comment by vodkapmp** [comment]
Everything works with setting it without "", it was trying to connect to `"hostname"` and not `hostname`
